spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dalaoshi   #localhost???  3306??mysql????   bluem???????
    username: root         #mysql???
    password: 132123       #mysql??
    driver-class-name: com.mysql.cj.jdbc.Driver   #jdbc???




mybatis:
  mapper-locations: mapper/*.xml    #????mapper?????????????mapper???